package cz.upce.nnpda.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import javax.sql.DataSource;

/**
 * Plain-JDBC DAO. Every method uses {@link PreparedStatement} and
 * try-with-resources so Connections, Statements and ResultSets are
 * always closed.
 */
public class StudentDao {

    private final DataSource dataSource;

    public StudentDao(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public void createTable() throws SQLException {
        String ddl = """
                CREATE TABLE IF NOT EXISTS students (
                    id BIGSERIAL PRIMARY KEY,
                    first_name VARCHAR(100) NOT NULL,
                    last_name VARCHAR(100) NOT NULL,
                    email VARCHAR(200) NOT NULL UNIQUE
                )
                """;
        // H2 in PostgreSQL compatibility mode understands BIGSERIAL via IDENTITY fallback,
        // so keep a portable variant for tests is unnecessary: H2 2.x supports BIGSERIAL
        // only in regular mode partially; use IDENTITY if needed. We try standard DDL first.
        try (Connection con = dataSource.getConnection();
             Statement st = con.createStatement()) {
            try {
                st.execute(ddl);
            } catch (SQLException e) {
                // Fallback for H2: use IDENTITY instead of BIGSERIAL.
                st.execute("""
                        CREATE TABLE IF NOT EXISTS students (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            first_name VARCHAR(100) NOT NULL,
                            last_name VARCHAR(100) NOT NULL,
                            email VARCHAR(200) NOT NULL UNIQUE
                        )
                        """);
            }
        }
    }

    public Student insert(Student student) throws SQLException {
        String sql = "INSERT INTO students (first_name, last_name, email) VALUES (?, ?, ?)";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, student.getFirstName());
            ps.setString(2, student.getLastName());
            ps.setString(3, student.getEmail());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    student.setId(keys.getLong(1));
                }
            }
        }
        return student;
    }

    public Optional<Student> findById(long id) throws SQLException {
        String sql = "SELECT id, first_name, last_name, email FROM students WHERE id = ?";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapRow(rs));
                }
                return Optional.empty();
            }
        }
    }

    public List<Student> findAll() throws SQLException {
        String sql = "SELECT id, first_name, last_name, email FROM students ORDER BY id";
        List<Student> result = new ArrayList<>();
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                result.add(mapRow(rs));
            }
        }
        return result;
    }

    public boolean update(Student student) throws SQLException {
        String sql = "UPDATE students SET first_name = ?, last_name = ?, email = ? WHERE id = ?";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, student.getFirstName());
            ps.setString(2, student.getLastName());
            ps.setString(3, student.getEmail());
            ps.setLong(4, student.getId());
            return ps.executeUpdate() == 1;
        }
    }

    public boolean delete(long id) throws SQLException {
        String sql = "DELETE FROM students WHERE id = ?";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setLong(1, id);
            return ps.executeUpdate() == 1;
        }
    }

    public int deleteAll() throws SQLException {
        try (Connection con = dataSource.getConnection();
             Statement st = con.createStatement()) {
            return st.executeUpdate("DELETE FROM students");
        }
    }

    private static Student mapRow(ResultSet rs) throws SQLException {
        return new Student(
                rs.getLong("id"),
                rs.getString("first_name"),
                rs.getString("last_name"),
                rs.getString("email"));
    }
}
