// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const docsDir = path.join(path.dirname(fileURLToPath(import.meta.url)), 'src', 'content', 'docs');

function readTitle(filePath) {
	const text = fs.readFileSync(filePath, 'utf8');
	const fm = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
	if (!fm) return null;
	const line = fm[1].match(/^title:\s*(?:"([^"]*)"|'([^']*)'|(.+?))\s*$/m);
	if (!line) return null;
	return (line[1] ?? line[2] ?? line[3] ?? '').trim() || null;
}

function prettyName(basename) {
	return basename
		.split('-')
		.map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
		.join(' ');
}

/**
 * Build one collapsed dropdown group per subject in a semester directory.
 * Each dropdown contains the course "Overview" page and its "My Notes"
 * personal notebook page (generated by scripts/generate-subject-notes.mjs).
 */
function subjectGroups(subdir) {
	const absDir = path.join(docsDir, subdir);
	if (!fs.existsSync(absDir)) return [];
	return fs
		.readdirSync(absDir)
		.filter((f) => f.endsWith('.mdx') && !f.endsWith('-notes.mdx') && f !== 'index.mdx')
		.map((file) => {
			const base = file.replace(/\.mdx$/, '');
			return {
				base,
				title: readTitle(path.join(absDir, file)) || prettyName(base),
				slug: `${subdir}/${base}`,
			};
		})
		.sort((a, b) => a.title.localeCompare(b.title))
		.map((s) => ({
			label: s.title,
			collapsed: true,
			items: [
				{ label: 'Overview', slug: s.slug },
				{ label: 'My Notes', slug: `${s.slug}-notes` },
			],
		}));
}

function semester(label, subdir) {
	return { label, items: subjectGroups(subdir) };
}

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: 'My Docs',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/withastro/starlight' }],
			customCss: [
				'./src/styles/custom.css',
			],
			sidebar: [
				{
					label: 'Year 1: Required',
					items: [
						semester('Winter Semester (ZS)', 'year-1-required/winter'),
						semester('Summer Semester (LS)', 'year-1-required/summer'),
					]
				},
				{
					label: 'Year 1: Optional Required',
					items: [
						semester('Winter Semester (ZS)', 'year-1-optional/winter'),
						semester('Summer Semester (LS)', 'year-1-optional/summer'),
					]
				},
				{
					label: 'Year 2: Required',
					items: [
						semester('Winter Semester (ZS)', 'year-2-required/winter'),
						semester('Summer Semester (LS)', 'year-2-required/summer'),
					]
				},
				{
					label: 'Year 2: Optional',
					items: [
						semester('Winter Semester (ZS)', 'year-2-optional/winter'),
					]
				},
				{
					label: 'Optional Courses',
					items: [
						semester('Winter Semester (ZS)', 'optional/winter'),
						semester('Summer Semester (LS)', 'optional/summer'),
					]
				}
			],
		}),
	],
});
